from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "tractorSpriteMap.png"
OUTPUT = ROOT / "src" / "tractor_beam_data.asm"
FRAME_WIDTH = 48
FRAME_HEIGHT = 80
FRAME_X = (1, 51, 101)


def rgb_to_cpc_pen(rgb):
    if rgb in ((0, 0, 0), (64, 64, 64)):
        return 0
    if rgb in ((0, 104, 255), (0, 184, 255)):
        return 1
    if rgb == (0, 255, 255):
        return 4
    raise ValueError(f"Unsupported tractor sprite-map color: {rgb}")


def encode_mode0_byte(left, right):
    return (
        ((left & 1) << 7)
        | ((right & 1) << 6)
        | (((left >> 2) & 1) << 5)
        | (((right >> 2) & 1) << 4)
        | (((left >> 1) & 1) << 3)
        | (((right >> 1) & 1) << 2)
        | (((left >> 3) & 1) << 1)
        | ((right >> 3) & 1)
    )


def main():
    sheet = Image.open(SOURCE).convert("RGB")
    if sheet.size != (150, 82):
        raise ValueError(f"Expected 150x82 tractor sprite map, got {sheet.size}")

    lines = [
        ";; Generated by tools/extract_tractor_beam.py from assets/tractorSpriteMap.png.",
        ";; Each frame is a native 48x80 crop packed as CPC Mode 0 pixels.",
    ]
    for frame_number, x in enumerate(FRAME_X, start=1):
        frame = sheet.crop((x, 1, x + FRAME_WIDTH, 1 + FRAME_HEIGHT))
        preview = Image.new("RGB", (FRAME_WIDTH, FRAME_HEIGHT), "black")
        packed_rows = []
        for y in range(FRAME_HEIGHT):
            pens = [rgb_to_cpc_pen(frame.getpixel((px, y))) for px in range(FRAME_WIDTH)]
            packed_rows.append([
                encode_mode0_byte(pens[px], pens[px + 1])
                for px in range(0, FRAME_WIDTH, 2)
            ])
            for px, pen in enumerate(pens):
                if pen == 1:
                    preview.putpixel((px, y), (0, 0, 255))
                elif pen == 4:
                    preview.putpixel((px, y), (0, 255, 255))

        lines.append(f"tractor_beam_frame_{frame_number}:")
        for y, row in enumerate(packed_rows):
            lines.append("    defb " + ", ".join(f"#{byte:02X}" for byte in row) + f"  ; Line {y}")
        lines.append("")
        preview.save(ROOT / "assets" / f"tractor_beam_frame_{frame_number}.png")

    OUTPUT.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
